import GuestLayout from "@/layouts/GuestLayout";
import { Link, useForm } from "@inertiajs/react";
import { Button, Group, PinInput, Stack, Text, Title } from "@mantine/core";
import { FormEvent, useEffect } from "react";

function TwoFactorVerifyPage() {

    const { post, processing, errors, data, setData } = useForm({
        code: ''
    })

    useEffect(() => {
        if (data.code.length === 6) {
            post(route('two-factor.verify_store'));
        }
    }, [data.code])

    const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        post(route('two-factor.verify_store'));
    }

    return (
        <GuestLayout>
            <Stack gap="xl" align="center">
                <Stack gap={0} ta="center">
                    <Title>Two Factor Authentication</Title>
                    <Text maw={384}>
                        Enter the 6 digit code generated by your phone's authenticator application.
                    </Text>
                </Stack>
                <form onSubmit={handleSubmit}>
                    <Group justify="center">
                        <PinInput
                            length={6}
                            error={!!errors.code}
                            value={data.code}
                            onChange={(v) => setData('code', v)}
                            autoFocus
                        />
                        <Button
                            type="submit"
                            loading={processing}
                        >
                            Verify
                        </Button>
                    </Group>
                    <Text c="red" ta="center">
                        {errors.code}
                    </Text>
                </form>
                <Text c="dimmed" size="sm">
                    Lost your device? <Link href={route("two-factor.recover")}>Use a recovery code</Link>.
                </Text>
            </Stack>
        </GuestLayout>
    );
}

export default TwoFactorVerifyPage;
